"""Third Migration

Revision ID: b46f33fe29d3
Revises: f92099b9555d
Create Date: 2021-06-19 21:37:37.699030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46f33fe29d3'
down_revision = 'f92099b9555d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('blog_content', sa.Text(), nullable=True))
    op.add_column('blogs', sa.Column('blog_by', sa.String(), nullable=True))
    op.drop_column('blogs', 'post_content')
    op.drop_column('blogs', 'post_title')
    op.drop_column('blogs', 'post_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('post_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('post_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_by')
    op.drop_column('blogs', 'blog_content')
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###
