"""Second Migration

Revision ID: f92099b9555d
Revises: 52eefa8fb5ca
Create Date: 2021-06-19 17:26:51.959663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f92099b9555d'
down_revision = '52eefa8fb5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post_title', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('post_content', sa.Text(), nullable=True))
    op.add_column('blogs', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('post_by', sa.String(), nullable=True))
    op.drop_column('blogs', 'content')
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('blogs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'post_by')
    op.drop_column('blogs', 'posted_at')
    op.drop_column('blogs', 'post_content')
    op.drop_column('blogs', 'post_title')
    # ### end Alembic commands ###
